
GET http://localhost:3000/scy2lru7gj


###

POST http://localhost:3000/novo
Content-Type: application/json

{
    "url": "https://youtube.com"
}

###


GET http://localhost:3000/fds/scy2lru7gj