
GET http://localhost:3000/

###

POST http://localhost:3000/novo
Content-Type: application/json

{
    "url": "https://abc.xyz"
}

###
GET http://localhost:3000/fds/j4pop_xmkr

###
GET http://localhost:3000/lista